import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(602BE7B1-9DD8-4B20-A432-61BB6F44AA5C)
]
interface IEmbedApplication : IUnknown
{
	HRESULT Update(
		[in] float dt
	);

	HRESULT GetSurfaceHandle(
		[out] DWORD_PTR* surfaceHandle
	);

	HRESULT SetSurfaceSize(
		[in] unsigned int width,
		[in] unsigned int height
	);

	HRESULT NotifyMouseMove(
		[in] int posX,
		[in] int posY
	);

	HRESULT NotifyMouseWheel(
		[in] int posZ
	);

	HRESULT NotifyMouseDown();
	HRESULT NotifyMouseUp();

	HRESULT NotifyKeyDown(
		[in] unsigned int code
	);

	HRESULT NotifyKeyUp(
		[in] unsigned int code
	);

	HRESULT NotifyExternalCommand(
		[in] BSTR command,
		[out, retval] BSTR* result
	);

	HRESULT GetEvents(
		[out, retval] SAFEARRAY(BSTR)* result
	);
};
